wowhead:
  api:
    baseurl: ''

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shadowfury
    username: shadowfury
    password: shadowfury
  thymeleaf:
    cache: false

error:
  whitelabel:
    enabled: false

battlenet:
  urls:
    eu: https://eu.api.battle.net
    us: https://us.api.battle.net